services:
    - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build -t spekulant/docker-oracle-12c .
  - docker push spekulant/docker-oracle-12c
